// <auto-generated />
using System;
using MedicalAppBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalAppBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421212605_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicalAppBackend.Models.Appointments", b =>
                {
                    b.Property<int>("IdAppointment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAppointment"));

                    b.Property<DateTime?>("DateTimeAppointment")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int?>("IdCompany")
                        .HasColumnType("int");

                    b.Property<int?>("IdDoctor")
                        .HasColumnType("int");

                    b.Property<int?>("IdPatient")
                        .HasColumnType("int");

                    b.Property<int?>("InsuranceCompanyIdCompany")
                        .HasColumnType("int");

                    b.Property<bool?>("IsNewPatient")
                        .HasColumnType("bit");

                    b.Property<string>("PatientEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientIdPatient")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symptoms")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAppointment");

                    b.HasIndex("DoctorId");

                    b.HasIndex("InsuranceCompanyIdCompany");

                    b.HasIndex("PatientIdPatient");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.ChatMessages", b =>
                {
                    b.Property<int>("IdChatMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChatMessage"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdChat")
                        .HasColumnType("int");

                    b.Property<int?>("IdUserSender")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Report")
                        .HasColumnType("bit");

                    b.HasKey("IdChatMessage");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.Chats", b =>
                {
                    b.Property<int>("IdChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChat"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<bool?>("AdminReview")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdUserReciver")
                        .HasColumnType("int");

                    b.Property<int?>("IdUserSender")
                        .HasColumnType("int");

                    b.HasKey("IdChat");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.Consultations", b =>
                {
                    b.Property<int>("IdConsultation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConsultation"));

                    b.Property<int?>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int?>("IdDoctor")
                        .HasColumnType("int");

                    b.Property<int?>("IdMedicalRecord")
                        .HasColumnType("int");

                    b.Property<int?>("IdPatient")
                        .HasColumnType("int");

                    b.Property<int?>("MedicalRecordIdMedicalRecord")
                        .HasColumnType("int");

                    b.Property<string>("MedicationsList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MyDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientIdPatient")
                        .HasColumnType("int");

                    b.Property<string>("SymptomsList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tests")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdConsultation");

                    b.HasIndex("DoctorId");

                    b.HasIndex("MedicalRecordIdMedicalRecord");

                    b.HasIndex("PatientIdPatient");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.DiseaseList", b =>
                {
                    b.Property<int>("IdDiseaseList")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiseaseList"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("DescDiseaseList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgDiseaseList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleArDiseaseList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEnDiseaseList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleFrDiseaseList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeCategDiseaseList")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDiseaseList");

                    b.ToTable("DiseaseLists");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.Doctors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpecialityId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialityId");

                    b.HasIndex("UserId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.Documents", b =>
                {
                    b.Property<int>("IdDocument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocument"));

                    b.Property<string>("AttachmentDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateDocument")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionDocument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdMedicalRecord")
                        .HasColumnType("int");

                    b.Property<int?>("MedicalRecordIdMedicalRecord")
                        .HasColumnType("int");

                    b.Property<string>("TitleDocument")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDocument");

                    b.HasIndex("MedicalRecordIdMedicalRecord");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.InsuranceCompany", b =>
                {
                    b.Property<int>("IdCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompany"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ValidDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCompany");

                    b.ToTable("InsuranceCompanies");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.MedicalRecords", b =>
                {
                    b.Property<int>("IdMedicalRecord")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedicalRecord"));

                    b.Property<string>("BloodDraw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChronicDiseases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Height")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HereditaryDiseases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdPatient")
                        .HasColumnType("int");

                    b.Property<string>("MedicalCheckup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMedicalRecord");

                    b.HasIndex("IdPatient")
                        .IsUnique()
                        .HasFilter("[IdPatient] IS NOT NULL");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.MedicationList", b =>
                {
                    b.Property<int>("IdMedication")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMedication"));

                    b.Property<string>("AgeRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DaysToTaken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionMedication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HowToTake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shouldnotbetaken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SymptomesList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleMedication")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMedication");

                    b.ToTable("MedicationLists");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.Patients", b =>
                {
                    b.Property<int>("IdPatient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPatient"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNSS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("IdPatient");

                    b.HasIndex("UserId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.Prescription", b =>
                {
                    b.Property<int>("IdPerscription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPerscription"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DocumentIdDocument")
                        .HasColumnType("int");

                    b.Property<int?>("IdDocument")
                        .HasColumnType("int");

                    b.Property<string>("MedicationList")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPerscription");

                    b.HasIndex("DocumentIdDocument");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.Relationships", b =>
                {
                    b.Property<int>("IdRelationships")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRelationships"));

                    b.Property<int?>("IdPatient1")
                        .HasColumnType("int");

                    b.Property<int?>("IdPatient2")
                        .HasColumnType("int");

                    b.Property<string>("NotesRelationships")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Patient1IdPatient")
                        .HasColumnType("int");

                    b.Property<int?>("Patient2IdPatient")
                        .HasColumnType("int");

                    b.Property<string>("TitleRelationships")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRelationships");

                    b.HasIndex("Patient1IdPatient");

                    b.HasIndex("Patient2IdPatient");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TitleName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.Specialities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialityName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Specialities");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.Appointments", b =>
                {
                    b.HasOne("MedicalAppBackend.Models.Doctors", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId");

                    b.HasOne("MedicalAppBackend.Models.InsuranceCompany", "InsuranceCompany")
                        .WithMany("Appointments")
                        .HasForeignKey("InsuranceCompanyIdCompany");

                    b.HasOne("MedicalAppBackend.Models.Patients", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientIdPatient");

                    b.Navigation("Doctor");

                    b.Navigation("InsuranceCompany");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.Consultations", b =>
                {
                    b.HasOne("MedicalAppBackend.Models.Doctors", "Doctor")
                        .WithMany("Consultations")
                        .HasForeignKey("DoctorId");

                    b.HasOne("MedicalAppBackend.Models.MedicalRecords", "MedicalRecord")
                        .WithMany()
                        .HasForeignKey("MedicalRecordIdMedicalRecord");

                    b.HasOne("MedicalAppBackend.Models.Patients", "Patient")
                        .WithMany("Consultations")
                        .HasForeignKey("PatientIdPatient");

                    b.Navigation("Doctor");

                    b.Navigation("MedicalRecord");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.Doctors", b =>
                {
                    b.HasOne("MedicalAppBackend.Models.Specialities", "Speciality")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialityId");

                    b.HasOne("MedicalAppBackend.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Speciality");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.Documents", b =>
                {
                    b.HasOne("MedicalAppBackend.Models.MedicalRecords", "MedicalRecord")
                        .WithMany("Documents")
                        .HasForeignKey("MedicalRecordIdMedicalRecord");

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.MedicalRecords", b =>
                {
                    b.HasOne("MedicalAppBackend.Models.Patients", "Patient")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("MedicalAppBackend.Models.MedicalRecords", "IdPatient")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.Patients", b =>
                {
                    b.HasOne("MedicalAppBackend.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.Prescription", b =>
                {
                    b.HasOne("MedicalAppBackend.Models.Documents", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentIdDocument");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.Relationships", b =>
                {
                    b.HasOne("MedicalAppBackend.Models.Patients", "Patient1")
                        .WithMany()
                        .HasForeignKey("Patient1IdPatient");

                    b.HasOne("MedicalAppBackend.Models.Patients", "Patient2")
                        .WithMany()
                        .HasForeignKey("Patient2IdPatient");

                    b.Navigation("Patient1");

                    b.Navigation("Patient2");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.Doctors", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.InsuranceCompany", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.MedicalRecords", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.Patients", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Consultations");

                    b.Navigation("MedicalRecord");
                });

            modelBuilder.Entity("MedicalAppBackend.Models.Specialities", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
